FROM oven/bun:1

WORKDIR /usr/src/app

ARG DATABASE_URL
COPY ./package.json ./package.json
COPY ./bun.lock ./bun.lock
COPY ./packages ./packages
COPY ./turbo.json ./turbo.json


RUN bun install
COPY ./apps/web ./apps/web
RUN bun run db:generate
RUN DATABASE_URL=${DATABASE_URL} bun run build
EXPOSE 3001

CMD ["bun", "run", "start:web"]

  