FROM oven/bun:1-alpine

WORKDIR /usr/src/app

ARG DATABASE_URL
COPY ./package.json ./package.json
COPY ./bun.lock ./bun.lock
COPY ./packages ./packages
COPY ./turbo.json ./turbo.json
COPY ./app/web/package.json ./app/web/package.json


RUN bun install
COPY ./app/web ./app/web
RUN bun run db:generate
RUN echo "My build argument is: $DATABASE_URL"
RUN cd app/web && DATABASE_URL=${DATABASE_URL} bun run build
EXPOSE 3001

CMD ["bun", "run", "start:web"]

  