FROM oven/bun:1-alpine

WORKDIR /usr/src/app

COPY ./package.json ./package.json
COPY ./bun.lock ./bun.lock
COPY ./packages ./packages
COPY ./turbo.json ./turbo.json
COPY ./apps/backend/package.json ./apps/backend/package.json

RUN bun install
COPY ./apps/backend ./apps/backend
RUN bun run db:generate

EXPOSE 8080

CMD ["bun", "run", "start:backend"]

  