name: CI/CD for Backend
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/mono-backend:${{ github.sha }}

      - name: Setup SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.PRIVATE_SSH }}
          port: 22
          script: |
            # Clean up old Docker resources first
            sudo docker system prune -f
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/mono-backend:${{ github.sha }}
            sudo docker stop backend || true
            sudo docker rm backend || true
            sudo docker run -d --name backend -p 4040:8080 ${{ secrets.DOCKER_USERNAME }}/mono-backend:${{ github.sha }}
            # Remove old images (keep only 3 latest)
            sudo docker images | grep "mono-backend" | tail -n +4 | awk '{print $3}' | xargs sudo docker rmi -f || true
        

